### ISSUE TITLE
Shorthand doesn't work with self, globals, outer and locals

### ISSUE THREAD

**Issue by ayecue** [ayecue/greybel-vs#106]
```
Tokenizer = {}
Tokenizer.constructor = function()
  self.index = 0

  return self
end function

Tokenizer.nextIndex = function(offset = 1)
  self.index += offset
  return self.index
end function

x = new Tokenizer.constructor

x.nextIndex
```

Specifically `self.index += offset` doesn't work. `self.index = offset` works though.

**Comment by Olipro** [comment]
Perhaps you already know this, but it never hurts to mention:

The shorthand syntax is a new 2023 MiniScript feature. GreyHack does not support these operators since it's essentially the interpreter from back in Dec 2021.

Something like a "language version" option would be a good solution if you add support for this.

**Comment by ayecue** [comment]
Yeah GreyScript does not support that shorthand but though the greybel-transpiler `i += 1` gets transpiled to `i = i + 1` so as long you use the transform or build command you should be fine using `i += 1`.

**Comment by ayecue** [comment]
Fixed by https://github.com/ayecue/greybel-vs/pull/113.
