### ISSUE TITLE
Interpreter hangs after calling `launch` in a loop that should be impossible to get stuck in

### ISSUE THREAD

**Issue by Olipro** [ayecue/greybel-vs#112]
After doing an `scp` and calling `launch, the interpreter gets stuck in a very weird place:

![image](https://github.com/ayecue/greybel-vs/assets/1489693/47c3d10a-6f3c-4be7-8e26-a7e1a4757156)

It keeps going in this loop infinitely, but never actually executes `task`, stepping line by line doesn't result in us entering `task`. Printing `self._tasks` shows `[FUNCTION()]`

It should just be executing the task, since the way I use `get_custom_object` is pushing functions across the boundary.

Perhaps even more strangely, to even reach this function, it has to go through the arg parser in `main` but the breakpoint I have there is never hit. Very bizarre.

Only guess I have for this one is that passing funcRefs across the boundary upsets the interpreter state in some way.

**Comment by ayecue** [comment]
Hey thanks for reporting,

In the example you shared it will not actually pull anything from task. Here an example which can also be tested in MiniScript. 
```lua
test = [1,2,3]

while test.len > 0
    task = @test.pull
    task
end while
``` 
Since you you use the addressOf operator you do not actually execute the pull and even after when you call task it will not have the context of test anymore. Therefore it will essentially not do anything.

> Perhaps even more strangely, to even reach this function, it has to go through the arg parser in main but the breakpoint I have there is never hit. Very bizarre.

Could you share an example for this case please? I mean the part with not hitting the breakpoint?

**Comment by Olipro** [comment]
This was my fault, I'm obtaining the address of `pull` which of course is not what it should be doing.

Sorry for wasting your time on this one. Closing.
