### ISSUE TITLE
Greybel accepts invalid inline anonymous function definition

### ISSUE THREAD

**Issue by Olipro** [ayecue/greybel-vs#122]
Given:

```Lua
Foo = [function
  return 1
end function]
```

The code should fail to parse, the same is true of doing it in a map. Sorry if this is already fixed, as I'm on `1.9.3` - feel free to close it if so.

**Comment by ayecue** [comment]
Yeah this issue mainly exists due to the way how the parser works.

The original MiniScript parser uses back patching logic. That's why "vodoo" like this is possible in MiniScript.
```lua
Foo = {"test": function()}
	return 1
end function
```

Greybel doesn't do that it instead it uses the recursion to parse which results in more precise parsing at least IMO. Since
```lua
Foo = {
	"test": function()
		return 1
	end function
}
```
looks much more intended.

Anyway I agree though this to be changed at least for the sake of supporting MiniScript in the future. So yeah I will need to add the back patching logic to the Greybel parser. But for now this will be low prio.

**Comment by Olipro** [comment]
There's an open MiniScript issue about that particular flavour of insanity as it happens. I believe Joe intends to do something about it, sooner or later :)

**Comment by ayecue** [comment]
I see so this is the related issue right https://github.com/JoeStrout/miniscript/issues/100? Looks like the suggested fix would actually then work just like it currently works in Greybel. :)

**Comment by Olipro** [comment]
With any luck, hopefully that's exactly what'll happen.

I guess for now though, maybe transform it to (current) valid syntax by breaking it out into a named var?

**Comment by ayecue** [comment]
With the release of https://github.com/ayecue/greybel-vs/pull/191 Function blocks will now behave similar to MiniScript. I'll close the issue for now.
