### ISSUE TITLE
Missing support for many commands in web VSC instance

### ISSUE THREAD

**Issue by almostSouji** [ayecue/greybel-vs#173]
I can only use the following Greybel commands through the command browser:
![image](https://github.com/ayecue/greybel-vs/assets/26532370/a4fabc06-ac9a-46a2-a116-49f6c6ddcc10)

I can assign the other commands to keyboard shortcuts and use them that way, but that's rather unintuitive:

![image](https://github.com/ayecue/greybel-vs/assets/26532370/91262b75-f862-47be-958b-354ad44f3dd2)

VSCode `1.85.1`
Greybel VS `v2.1.18`

**Comment by ayecue** [comment]
Interesting for me all commands show up via the command prompt. Just wondering do you have a greyscript file open when doing this or are there no greyscript files open? I am asking that since the commands shown always depend on the context.

**Comment by almostSouji** [comment]
I am using the command from within a `.src` file

**Comment by ayecue** [comment]
Hm that is interesting. On my mac it displays all commands:
<img width="660" alt="Screenshot 2024-01-17 at 21 48 11" src="https://github.com/ayecue/greybel-vs/assets/2996761/625abb35-f695-4039-8a2a-792d3f50487a">

Which operation system are you using? Also do you use any UI extensions?

**Comment by almostSouji** [comment]
I cannot reproduce this on my local machine (with the same version of vscode and greybel) but only on a remote VSC instance.
Could this potentially have to do with trying to detect local game files? As the remote VSC runs on a Linux server that is the only idea I have left now. I've never had anything similar happen with other extensions since we switched to the official release.

I had a friend who also codes on the same instance (with little to no overlap in extensions) try it and he also gets 2 commands only (to exclude the possibility of one of my settings or other extensions conflicting)

**Comment by ayecue** [comment]
Okay I can replicate your issue on https://vscode.dev/. So the issue is that most commands are not supported in the web version of VSCode as it does not support the complete feature set of a local VSCode therefore I've put a filter in place for some commands so those are not available in web. The actual bug is that you can still select them in the keyboard shortcuts.

**Comment by ayecue** [comment]
Good point I'll take a look into those.

**Comment by ayecue** [comment]
I changed some of the flags regarding what commands should be displayed in web and which don't. It looks like most of the commands are now available.

**Comment by almostSouji** [comment]
![image](https://github.com/ayecue/greybel-vs/assets/26532370/850f87ac-ccb4-4501-974d-7111f029912b)

Are `beautify.write`, `build`, `minify.write`, `transform.write`, `debug.debugEditorContents` and `debug.runEditorContents` problematic?
especially minify, beautify, and build would be very useful (I currently opt to run these on local vsc, but I don't immediately see why they wouldn't work in the browser version)

running `v2.2.1`

**Comment by ayecue** [comment]
I can look into the transformations. It's just a bit difficult for me to test since I don't have a setup without releasing a new version since it'll only be available in https://vscode.dev/ when it's published. Could you maybe share your setup for the remote VSC since it would help me to test it properly.

Build will most likely not work since the FS probably is not supported at least when I tested web with build it wouldn't work correctly. Also running code didn't work either from my testing since apparently debuggers are not supported in web vscode.

**Comment by almostSouji** [comment]
Ah, I see, vscode.dev indeed has more restrictions
the standalone vscode server is very close to the native client (as you are running it directly on your server)
documentation'setup would be <https://code.visualstudio.com/docs/remote/vscode-server>
instead of `code tunnel` we use `code serve-web` which means we are also hosting the frontend instead of using vscode.dev

**Comment by ayecue** [comment]
Sorry that it took some time but after some testing around it seems like all the functionality is working fine via `code serve-web` even the importing is working fine. As a result I removed all the restrictions I've put on the extension if it's displayed in web.

So from my testing everything should be visible now. In case there is still something remaining feel free to reopen this ticket.

**Comment by almostSouji** [comment]
No worries, thanks for looking into it at all! You rock!
