### ISSUE TITLE
I did notice this...really not an issue but

### ISSUE THREAD

**Issue by linuxgruven** [ayecue/greybel-vs#246]
I looks like your plugin is reading inside of double quotes code example
"msg":{"c":"Check your syntax, there is no command [ ","s":"Check your syntax, there is no switch [ "}
![code](https://github.com/user-attachments/assets/0277645b-3c55-418c-960a-9365771e3b21)
It started doing this after your .8 update..code compiles as it has been there for 2-3 years. Can close as this is not an issue for me

**Comment by ayecue** [comment]
But this is only syntax highlighting right? Since when I tested it there was no actual issue beside syntax highlighting also it only seems to occur when I update the extension and then click on restart extension. When I reload the file though this issue disappers.

Additionally this also occurs to me prior to the `.8` update.

**Comment by linuxgruven** [comment]
Yeah

**Comment by linuxgruven** [comment]
Compiles fine

**Comment by ayecue** [comment]
Alright closing the issue for now.
