### ISSUE TITLE
Specifying the Working directory when executing scripts

### ISSUE THREAD

**Issue by Olipro** [ayecue/greybel-vs#82]
Hi there, excellent extension!

1. Perhaps I'm missing something, but I can't find a way to specify the working directory when running scripts so that it resolves the relative paths of `include_code` appropriately.

Also, if you have time to answer I have these additional questions:

2. Is there a way to prevent being prompted to input arguments everytime I run/debug a script.
3. Would it be possible to replace or extend `include_code` parsing with a lookup for a special comment instead like `// @dep:pathTo/script.src` - I can probably implement this myself if you point me in the right direction. Bit of a personal request since I built my own dependency-walker for building scripts :)

Thanks!

**Comment by ayecue** [comment]
Hey, thanks :)

> Perhaps I'm missing something, but I can't find a way to specify the working directory when running scripts so that it resolves the relative paths of include_code appropriately.

Do you mean `import_code`? Also do you mean running it with the provided interpreter or ingame?

> Is there a way to prevent being prompted to input arguments everytime I run/debug a script.

No currently there is no option to do that. But I can add a flag if that fits your needs. I could also add a setting where you can define your default execution args.

> Would it be possible to replace or extend include_code parsing with a lookup for a special comment instead like // @dep:pathTo/script.src - I can probably implement this myself if you point me in the right direction. Bit of a personal request since I built my own dependency-walker for building scripts :)

So currently greybel supports 3 different kind of imports. 
* `import_code` can be used so that you can get bypass the 160k char limit, also via the installer you can actually pretty much generate all the files ingame. Another feature is that you can actually nest your `import_code` that's done by moving `import_code` into the entry file, it will then sort the imports in the order in which those are required. Keep in mind though that this only really works with import_code is on top of files since otherwise the order cannot be guaranteed
* `#import namespace from path` will bundle a dependency into the entry file, upside is that imports won't be included multiple times but it won't help bypass the 160k char limit
* `#include path` is just a simple copy file content and put it where it got included

So `import_code` will probably stay how it is. But I could change `#import` and `#include` so that it takes `//` instead of `#`. Would that work for you?

**Comment by Olipro** [comment]
> Do you mean import_code? Also do you mean running it with the provided interpreter or ingame?
Yes, I did indeed. In the interpreter, not the game. I promise I won't come here for in-game issues 😄

To detail further. I have my code broken up into `src` and `test` folders. The build always seems to execute relative to the location of the file - if I could specify the wdir then it would be avoid filling my scripts with `import_code("../src/Foo.src")`

> No currently there is no option to do that. But I can add a flag if that fits your needs. I could also add a setting where you can define your default execution args.

Yep that'd be great. While you're at it, if it's not too much work to add an option to silence the error popups, that would also be good. I just look at the terminal anyway - but of all the things to find time for, this is the least needy.

> So import_code will probably stay how it is. But I could change #import and #include so that it takes // instead of #. Would that work for you?

Anything that's behind a `//` comment would be perfect.

**Comment by ayecue** [comment]
> To detail further. I have my code broken up into src and test folders. The build always seems to execute relative to the location of the file - if I could specify the wdir then it would be avoid filling my scripts with import_code("../src/Foo.src")

Okay I get your point now. So there is a related issue https://github.com/ayecue/greybel-js/issues/104 but this might gonna take a bit more time. But for the vscode extension I could actually use the vscode workspace as a reference. So I might just gonna do that in the meantime.

> Yep that'd be great. While you're at it, if it's not too much work to add an option to silence the error popups, that would also be good. I just look at the terminal anyway - but of all the things to find time for, this is the least needy.

I can add another flag to silence the popups. Shouldn't be much of a hassle.

> Anything that's behind a // comment would be perfect.

Alright I'll add the `//` prefix as an alternative then to `#`.

**Comment by ayecue** [comment]
I created two follow up issues for each enhancement. Those will be in another PR in the future. For https://github.com/ayecue/greybel-vs/pull/83 I'll only include the fix from https://github.com/ayecue/greybel-js/issues/108 and the options related to args and error popups.

**Comment by ayecue** [comment]
Alright so both #84 and #85 should be implemented now.

To use the vscode workspace directory within imports just put a slash in front of the import e.g. `/src/file.src` and then it will use the root path of your workspace.

I'll keep the ticket open for now until you confirm that the features got implemented as requested.

**Comment by Olipro** [comment]
Tested and confirmed that the leading / works.
