### ISSUE TITLE
Support MiniScript files (.ms)

### ISSUE THREAD

**Issue by juh9870** [ayecue/greybel-vs#96]
It would be great to have a support for MiniScipt files too.

Grey Script is based on MiniScript, and as far as I'm aware, it has no differences compared to the 2021 version of MiniScript.

A simple change would be to include the extension to cover `.ms` files, but ideally, some changes to autocompletion are needed to make the extension not to suggest GreyHack-only APIs

**Comment by ayecue** [comment]
Hey so when it comes to syntax you are right there are no differences to GreyScript. But there are the following differences:
- basic MiniScript intrinsics don't match 100%
- GreyScript has "import_code" which is kind of like an ingame on "build" include

Additionally most of the functionality provided by this extension is pretty much focused on GreyScript and probably doesn't have any purpose for MiniScript. I mean I can just add the `.ms` extension but not sure how much this extension can help with actual MiniScript coding.

But I think it would be pretty "easy" to create a new extension reusing some of the packages used within this extension. Also I am not sure which of the features this extension provides you are looking for?

**Comment by ayecue** [comment]
I see so just wondering which features specifically are we speaking about? Automcomplete, HoverDocs, Diagnostics, Interpreter etc? Just to get an idea which packages are required.

Yeah I think this is specifically the issue. I think there needs to be some decoupling done in order to make this not horrible to maintain.

**Comment by Olipro** [comment]
I'd frame it as _"everything that isn't GreyHack specific"_ like the game intrinsics. The debugger is especially powerful since you can't do that with the official MiniScript implementations.

Command-line MiniScript/MiniMicro also has some additional intrinsics like `File` and `Input` - the former is a `map` with a bunch of native functions that let you access your computer's actual filesystem, Input is a bit like `user_input`. But this is also the exact sort of stuff you can decouple from the core interpreter and potentially allow mixing and matching with GreyScript intrinsics.

e.g. when firing up the interpreter/debugger, you have some options defined somewhere to tell it which intrinsics package(s) should be loaded into the script VM.

**Comment by juh9870** [comment]
What is good to have:
- Auto formatter (beautify). I have autoformatter in my fork of the extension, but it's regex-based, not actually parsing syntax tree,
- Autocomplete. Autocomplete for intrinsics and standard library would be ideal.
- Syntax error detection. It's a big one
- Interpreter... Not sure, it may be useful for "raw" miniscript, but a lot of use cases are for MiniMicro and so it's probably not very useful
- Code bundling. This extension seems to have pretty good bundling capabilities, which are pretty useful outside GH too, to avoid issues with the default MiniMicro `import`, which behaves more like `include`

**Comment by Olipro** [comment]
> Interpreter... Not sure, it may be useful for "raw" miniscript, but a lot of use cases are for MiniMicro or embedded environments and so it's probably not very useful

Being able to introspect your code, is tremendously useful - create a fake/mock of whatever MiniMicro function(s) you need and fire up the debugger.

**Comment by ayecue** [comment]
> I'd frame it as "everything that isn't GreyHack specific" like the game intrinsics. The debugger is especially powerful since you can't do that with the official MiniScript implementations.

I see so that means I need to decouple the lexer, parser, transpiler and interpreter. I mean I could mix them but that would kinda make it probably confusing to work with.

Lexer, parser, transpiler and interpreter are pretty simple to decouple since I would just need to decouple `import_code` I believe. I also probably need to switch it's dependency order. Since right now it's greyscript-core > greybel-core. So in the future it should be more like miniscript-core > greybel-core > greyscript-core.

> Command-line MiniScript/MiniMicro also has some additional intrinsics like File and Input - the former is a map with a bunch of native functions that let you access your computer's actual filesystem, Input is a bit like user_input. But this is also the exact sort of stuff you can decouple from the core interpreter and potentially allow mixing and matching with GreyScript intrinsics.

Adding intrinsics shouldn't be difficult since that part is already quite decoupled. So for that there would be just new intrinsics packages required and as you mentioned somekind of intrinsic package selection.

> Syntax error detection. It's a big one

For this I would probably need to add also an option to select the diagnostics syntax. Since there are some minor differences. So GreyScript for example allows non literal default values in args (which is broken) but still supported.

> Code bundling. This extension seems to have pretty good bundling capabilities, which are pretty useful outside GH too, to avoid issues with the default MiniMicro import, which behaves more like include, or for embedded environments that don't have import functionality.

For this I would probably need some input or look into on how the bundling should work for MiniMicro and MiniScript. Are there any differences?

----
Anyway I am up to do some decoupling if it helps the MiniScript community. I'm just not yet sure on how I am gonna do it. I may going to create a new extension if I see it becomes too much of a hassle to put it into this one. This may gonna take some time though.

**Comment by ayecue** [comment]
I've added `.ms` as an extension in the meantime https://github.com/ayecue/greybel-vs/pull/98/commits/0d712d3d79306a2e226d6ea0553982f0635905ac. Should be available as soon https://github.com/ayecue/greybel-vs/pull/98 is merged.

**Comment by juh9870** [comment]
Yeah, seems reasonable. On the quick glance, the only thing that is not a part of standard MiniScript is `exit` with string argument, but that is easily resolved just by defining a polyfill.

**Comment by ayecue** [comment]
Yeah I am currently working on changing the transpiler to only support MiniScript as a default. Everything related to GreyScript will be decoupled into a new package.

Doing the same for the [meta](https://github.com/ayecue/miniscript-meta) and [parser/lexer](https://github.com/ayecue/miniscript-core) part.

After the transpiler is decoupled I'll then also decouple the interpreter.

**Comment by ayecue** [comment]
Okay I've finished porting greybel-vs to miniscript-vs. It's available here https://github.com/ayecue/miniscript-vs
